services:
  panel:
    image: ghcr.io/ton-bypass/panel:latest
    restart: unless-stopped
    network_mode: host
    env_file: .env
    environment:
      UVICORN_HOST: ${UVICORN_HOST:-0.0.0.0}
      UVICORN_PORT: ${UVICORN_PORT:-8000}
    volumes:
      - /var/lib/marzban:/var/lib/marzban
